#!/bin/bash

build() {
  npm i
}

test() {
  ./node_modules/.bin/mocha ${@} \
    --recursive \
    'src/**/*.spec.js'
}

cli() {
  node ./src/runtime/cli/index.js
}

server() {
  node ./src/runtime/broker/index.js
}

$1 ${@:2}
