#!/bin/bash

build() {
  npm i
}

test() {
  ./node_modules/.bin/mocha ${@} \
    --recursive \
    'src/**/*.spec.js'
}

cli() {
  node --inspect-brk=0.0.0.0 ./src/client/cli.js ${@}
}

server() {
  node ./src/runtime/broker/index.js ${@}
}

$1 ${@:2}
