#!/bin/bash

build() {
  npm i
}

test() {
  ./node_modules/.bin/mocha ${@} \
    --recursive \
    'src/**/*.spec.js'
}

cli() {
  # --inspect-brk=0.0.0.0
  node ./src/client/cli.js ${@}
}

compile() {
  docker build -t jotaen/crypto-yahtzee .
}

$1 ${@:2}
