name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build project
        run: docker build -t jotaen/crypto-yahtzee .
      - name: Run tests
        run: docker run --rm jotaen/crypto-yahtzee test
      - name: Publish on Docker Hub
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REGISTRY_KEY: ${{ secrets.DOCKER_REGISTRY_KEY }}
        run: |
          docker login --username jotaen --password $DOCKER_REGISTRY_KEY
          docker push jotaen/crypto-yahtzee
